[project]
name = "spectra"
version = "0.1.0"
description = "Spectra is an MCP server for converting colors between different spaces."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "coloraide>=5.1",
    "fastmcp>=2.13.0.2",
]
